export enum AppointmentType {
  URGENT = 'URGENT',

  MORNING = 'MORNING',

  AFTERNOON = 'AFTERNOON',

  EVENING = 'EVENING',

  TO_BE_COLLECTED_FROM_CLIENT = 'TO_BE_COLLECTED_FROM_CLIENT',

  GOV = 'GOV',

  COOPERATE = 'COOPERATE',
}
