export enum TenantBusinessType {
  CORPORATE = 'CORPORATE',

  SME = 'SME',

  NON_PROFIT = 'NON_PROFIT',

  GOVERNMENT = 'GOVERNMENT',

  EDUCATIONAL = 'EDUCATIONAL',

  AUTOMOBILE_REPAIR = 'AUTOMOBILE_REPAIR',
}
