export enum EnrollmentStatus {
  PENDING = 'PENDING',
  ENROLLED = 'ENROLLED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  WITHDRAWN = "WITHDRAWN",
  GRADUATED = "GRADUATED",
  SUSPENDED = "SUSPENDED",
}

